package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// Reported from real use on 2026-08-20:
//
//	PS> npm install -g npm@latest
//	ℹ Verifying package "npm"...
//	ℹ Scanning OSV database for known vulnerabilities...
//	✘ Vulnerability Scan Alert: Found active vulnerabilities!
//	? Proceed with installation despite active vulnerabilities? [y/N]: y
//	✘ Global installs (-g) can't run inside the sandbox.
//
// The refusal depends only on the flags, so it was knowable before any of that.
// Instead the user waited on a network scan, was shown a security prompt, agreed
// to it, and only then learned the command could never have run. Approving a
// vulnerability warning for nothing is worse than the delay: it trains people to
// click through the prompt that matters.
func TestGlobalInstallIsDetectedWithoutRunningAnything(t *testing.T) {
	cases := []struct {
		cmd  string
		args []string
		want bool
	}{
		{"npm", []string{"install", "-g", "npm@latest"}, true},
		{"npm", []string{"install", "--global", "typescript"}, true},
		{"npm", []string{"i", "-g", "eslint"}, true},
		{"yarn", []string{"global", "add", "typescript"}, true},
		{"yarn", []string{"global", "remove", "typescript"}, true},
		{"yarn", []string{"--silent", "global", "add", "typescript"}, true},
		// A package literally named "global" is not a global install.
		{"yarn", []string{"add", "global"}, false},
		{"npm", []string{"install", "lodash"}, false},
		{"npm", []string{"install"}, false},
		{"npm", []string{"run", "build"}, false},
	}
	for _, tc := range cases {
		if got := isGlobalInstall(tc.cmd, tc.args); got != tc.want {
			t.Errorf("isGlobalInstall(%q, %v) = %v, want %v", tc.cmd, tc.args, got, tc.want)
		}
	}
}

// The refusal tells the user to run `nvx --no-sandbox ...`. That is only useful
// if `nvx` is a command their shell can find.
//
// In the report above it was not: the shims in ~/.nvx/bin had been generated by a
// source build, so they pointed into the build tree and no nvx.exe was installed
// beside them. The advice was unfollowable -- "The term 'nvx' is not recognized"
// -- which is the worst shape for an error message, because it looks like the
// user's mistake.
func TestNvxHintNamesSomethingRunnable(t *testing.T) {
	hint := installedNvxHint()
	if hint == "" {
		t.Fatal("the hint is empty; the refusal would name no command at all")
	}

	if hint == "nvx" {
		// Only correct when the shell can actually resolve it. LookPath is what
		// installedNvxHint consults, so agreeing here is not circular: it asserts
		// the plain name is never returned when it would not resolve.
		if _, err := exec.LookPath("nvx"); err != nil {
			t.Fatalf("hint is the bare name %q but it does not resolve on PATH: %v", hint, err)
		}
		return
	}

	// Otherwise it must be a path that exists, since the user will retype it.
	path := strings.Trim(hint, `"`)
	if _, err := os.Stat(path); err != nil {
		t.Errorf("hint %q is neither a resolvable command nor an existing file: %v", hint, err)
	}
	if runtime.GOOS == "windows" && strings.ContainsAny(path, " \t") && !strings.HasPrefix(hint, `"`) {
		t.Errorf("hint %q contains a space but is unquoted; pasting it would split the command", hint)
	}
	if filepath.Base(path) == "" {
		t.Errorf("hint %q has no command component", hint)
	}
}

// yarn's `global add` writes to the same shared prefix as npm's -g, and was not
// recognised until 2026-08-20 because only the flags were matched. It fell
// through to the sandbox and failed partway with the confusing permission error
// isGlobalInstall exists to replace.
func TestYarnGlobalSubcommandIsRecognised(t *testing.T) {
	if !isGlobalInstall("yarn", []string{"global", "add", "typescript"}) {
		t.Error("`yarn global add` is not treated as a global install; it will be contained " +
			"and then fail with a permission error instead of the clear refusal npm -g gets")
	}
	// Position matters: this installs a package called "global".
	if isGlobalInstall("yarn", []string{"add", "global"}) {
		t.Error("`yarn add global` was refused; a package named \"global\" is not a global install")
	}
}
