package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// Reported from real use on 2026-08-20:
//
//	PS> npm install -g npm@latest
//	ℹ Verifying package "npm"...
//	ℹ Scanning OSV database for known vulnerabilities...
//	✘ Vulnerability Scan Alert: Found active vulnerabilities!
//	? Proceed with installation despite active vulnerabilities? [Y/n]: y
//	✘ Global installs (-g) can't run inside the sandbox.
//
// The refusal depends only on the flags, so it was knowable before any of that.
// Instead the user waited on a network scan, was shown a security prompt, agreed
// to it, and only then learned the command could never have run. Approving a
// vulnerability warning for nothing is worse than the delay: it trains people to
// click through the prompt that matters.
func TestGlobalInstallIsDetectedWithoutRunningAnything(t *testing.T) {
	cases := []struct {
		cmd  string
		args []string
		want bool
	}{
		{"npm", []string{"install", "-g", "npm@latest"}, true},
		{"npm", []string{"install", "--global", "typescript"}, true},
		{"npm", []string{"i", "-g", "eslint"}, true},
		{"npm", []string{"install", "lodash"}, false},
		{"npm", []string{"install"}, false},
		{"npm", []string{"run", "build"}, false},
	}
	for _, tc := range cases {
		if got := isGlobalInstall(tc.cmd, tc.args); got != tc.want {
			t.Errorf("isGlobalInstall(%q, %v) = %v, want %v", tc.cmd, tc.args, got, tc.want)
		}
	}
}

// The refusal tells the user to run `nvx --no-sandbox ...`. That is only useful
// if `nvx` is a command their shell can find.
//
// In the report above it was not: the shims in ~/.nvx/bin had been generated by a
// source build, so they pointed into the build tree and no nvx.exe was installed
// beside them. The advice was unfollowable -- "The term 'nvx' is not recognized"
// -- which is the worst shape for an error message, because it looks like the
// user's mistake.
func TestNvxHintNamesSomethingRunnable(t *testing.T) {
	hint := installedNvxHint()
	if hint == "" {
		t.Fatal("the hint is empty; the refusal would name no command at all")
	}

	if hint == "nvx" {
		// Only correct when the shell can actually resolve it. LookPath is what
		// installedNvxHint consults, so agreeing here is not circular: it asserts
		// the plain name is never returned when it would not resolve.
		if _, err := exec.LookPath("nvx"); err != nil {
			t.Fatalf("hint is the bare name %q but it does not resolve on PATH: %v", hint, err)
		}
		return
	}

	// Otherwise it must be a path that exists, since the user will retype it.
	path := strings.Trim(hint, `"`)
	if _, err := os.Stat(path); err != nil {
		t.Errorf("hint %q is neither a resolvable command nor an existing file: %v", hint, err)
	}
	if runtime.GOOS == "windows" && strings.ContainsAny(path, " \t") && !strings.HasPrefix(hint, `"`) {
		t.Errorf("hint %q contains a space but is unquoted; pasting it would split the command", hint)
	}
	if filepath.Base(path) == "" {
		t.Errorf("hint %q has no command component", hint)
	}
}

// A gap found while writing the test above, recorded rather than fixed because
// the report was about npm and widening the change would bury it.
//
// globalInstallFlags is {-g, --global}, so `yarn global add <pkg>` -- yarn's own
// spelling, a subcommand rather than a flag -- is not recognised. It is therefore
// contained, and then fails partway through with the confusing permission error
// that isGlobalInstall's doc comment says the check exists to avoid. `pnpm add
// --global` is covered because pnpm uses the flag.
//
// This asserts today's behaviour so the gap is visible and the next change to
// isGlobalInstall has to decide about it deliberately. If someone fixes yarn,
// this test fails and the comment tells them why it was written that way.
func TestYarnGlobalSubcommandIsNotYetRecognised(t *testing.T) {
	if isGlobalInstall("yarn", []string{"global", "add", "typescript"}) {
		t.Skip("yarn's `global add` is now recognised -- delete this test and add the case " +
			"to TestGlobalInstallIsDetectedWithoutRunningAnything")
	}
	t.Log("known gap: `yarn global add` is contained and fails with a permission error " +
		"instead of the clear refusal npm -g gets")
}
