package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

const projectBinShimDirName = "project-bin"

// findProjectRoot walks upward from startDir looking for package.json.
func findProjectRoot(startDir string) string {
	dir, err := filepath.Abs(startDir)
	if err != nil {
		dir = startDir
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "package.json")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

// projectBinDir returns the directory of nvx wrappers for a project's
// node_modules/.bin, which `nvx use` puts near the front of PATH.
//
// It lives under nvxHome, NOT inside the project, and that is the whole point.
// It used to be <project>/.nvx/project-bin: a directory a contained install can
// write to, sitting second on the developer's PATH, ahead of System32. A
// postinstall could drop a file named `git` there and wait. The next `git` the
// developer typed ran that file with their full user token -- every credential
// store, every project, unrestricted network -- with no sandbox involved at all.
// The containment was not broken; it was routed around by a directory nvx itself
// put on PATH. Measured end to end in both PowerShell and Git Bash.
//
// Under nvxHome the sandbox cannot write it: guest homes and the working
// directory are granted, and nvxHome itself is not.
//
// Keyed by a hash of the project path so two projects cannot collide, and so the
// directory name discloses nothing about where the project is.
func projectBinDir(projectRoot, nvxHome string) string {
	sum := sha256.Sum256([]byte(strings.ToLower(filepath.Clean(projectRoot))))
	return filepath.Join(nvxHome, projectBinShimDirName, hex.EncodeToString(sum[:])[:16])
}

// shimWouldShadowAnExistingCommand reports whether creating a project-bin shim
// for name would shadow an executable that already exists outside this project.
//
// Relocating the directory is necessary but not sufficient: node_modules/.bin is
// itself writable by a contained install, so a postinstall can create
// node_modules/.bin/git and wait for the next regeneration to shim it. Refusing
// to shadow closes that half.
//
// The cost is deliberate and worth stating: if you have a global tool of the same
// name, the project-local one no longer wins through nvx. `npx <tool>` still runs
// the local one, contained. Letting an attacker-writable directory take
// precedence over system commands on an interactive PATH is not a trade worth
// making for that convenience.
func shimWouldShadowAnExistingCommand(name, projectRoot, shimDir string) bool {
	resolved := resolveCommandOnPath(name, os.Getenv("PATH"))
	if resolved == "" {
		return false // nothing to shadow: this is the ordinary local-CLI case
	}
	dir := filepath.Dir(resolved)
	if dirWithin(dir, projectRoot) {
		return false // the project's own copy, which is what we are wrapping
	}
	if dirsEqual(dir, shimDir) {
		return false // a shim we generated on a previous run
	}
	return true
}

func projectNodeModulesBin(projectRoot string) string {
	return filepath.Join(projectRoot, "node_modules", ".bin")
}

// generateProjectBinShims creates nvx wrappers for executables in node_modules/.bin.
func generateProjectBinShims(projectRoot, nvxHome string) error {
	binDir := projectNodeModulesBin(projectRoot)
	entries, err := os.ReadDir(binDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	shimDir := projectBinDir(projectRoot, nvxHome)
	if err := os.MkdirAll(shimDir, 0700); err != nil {
		return err
	}

	// These shims are regenerated by every `npm install`, at which point this
	// process is the npm.exe shim; the file must name nvx, not npm.exe.
	exePath, err := selfNvxBinary()
	if err != nil {
		exePath = filepath.Join(nvxHome, "nvx")
	}

	seen := map[string]bool{}
	kept := map[string]bool{}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() {
			continue
		}
		base := strings.TrimSuffix(name, filepath.Ext(name))
		if base == "" || seen[base] {
			continue
		}
		seen[base] = true
		if shimWouldShadowAnExistingCommand(base, projectRoot, shimDir) {
			// A name that already resolves elsewhere is not a project CLI we can
			// safely front. Skipping is what stops a planted node_modules/.bin/git
			// from becoming a PATH entry ahead of the real one.
			continue
		}
		if err := writeProjectBinShim(shimDir, exePath, base); err != nil {
			return err
		}
		kept[base] = true
	}

	pruneProjectBinShims(shimDir, kept)
	return nil
}

// pruneProjectBinShims deletes wrappers that no longer correspond to anything in
// node_modules/.bin.
//
// Generation only ever added files before, so a shim outlived the package that
// justified it -- and any file that found its way into the directory stayed on
// PATH indefinitely. Rebuilding the set on every run means the directory holds
// what the project currently has and nothing else.
func pruneProjectBinShims(shimDir string, kept map[string]bool) {
	entries, err := os.ReadDir(shimDir)
	if err != nil {
		return
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		base := strings.TrimSuffix(e.Name(), filepath.Ext(e.Name()))
		if kept[base] {
			continue
		}
		_ = os.Remove(filepath.Join(shimDir, e.Name()))
	}
}

func writeProjectBinShim(shimDir, exePath, cmd string) error {
	posix := fmt.Sprintf("#!/bin/sh\nexec %s shim %s \"$@\"\n", quotePOSIXShell(exePath), quotePOSIXShell(cmd))
	if runtime.GOOS != "windows" {
		return writeExecutableFile(filepath.Join(shimDir, cmd), []byte(posix))
	}

	content := fmt.Sprintf("@echo off\r\n%s shim %s %%*\r\n", quoteWindowsBatchArg(exePath), quoteWindowsBatchArg(cmd))
	if err := writeExecutableFile(filepath.Join(shimDir, cmd+".cmd"), []byte(content)); err != nil {
		return err
	}
	// And the extensionless one, for bash.
	//
	// The same fix landed on ~/.nvx/bin and stopped one directory short of here,
	// so `vite` or `eslint` from a project's own node_modules still resolved past
	// nvx in Git Bash with "command not found" — same shell, same cause, same
	// release. bash does not consult PATHEXT: it looks for a file named exactly
	// `vite`.
	return writeExecutableFile(filepath.Join(shimDir, cmd), []byte(posix))
}

func isProjectBinCommand(cmdName string) bool {
	cwd, err := os.Getwd()
	if err != nil {
		return false
	}
	root := findProjectRoot(cwd)
	if root == "" {
		return false
	}
	binPath := filepath.Join(projectNodeModulesBin(root), cmdName)
	if runtime.GOOS == "windows" {
		if _, err := os.Stat(binPath + ".cmd"); err == nil {
			return true
		}
		if _, err := os.Stat(binPath + ".ps1"); err == nil {
			return true
		}
	}
	if _, err := os.Stat(binPath); err == nil {
		return true
	}
	return false
}

func resolveProjectBinCommand(cmdName string) string {
	cwd, err := os.Getwd()
	if err != nil {
		return ""
	}
	root := findProjectRoot(cwd)
	if root == "" {
		return ""
	}
	binDir := projectNodeModulesBin(root)
	if runtime.GOOS == "windows" {
		for _, ext := range []string{".cmd", ".ps1", ""} {
			p := binDir + string(os.PathSeparator) + cmdName + ext
			if ext == "" {
				p = filepath.Join(binDir, cmdName)
			} else {
				p = filepath.Join(binDir, cmdName+ext)
			}
			if _, err := os.Stat(p); err == nil {
				return p
			}
		}
		return ""
	}
	p := filepath.Join(binDir, cmdName)
	if _, err := os.Stat(p); err == nil {
		return p
	}
	return ""
}
